### ISSUE TITLE
Install and Class Only

### ISSUE THREAD

**Issue by Savagepvppanda** [willuwontu/ShieldClass#3]
When install this it doesn't show up in the card's menu. Whenever I try to play with classes only this class doesn't show up. How do i correctly install this class? How do I make it too where this class shows up in classes only?

**Comment by willuwontu** [comment]
It's not compatible with FFC and Classes Manager, instead use PFFC and Classes Manager Reborn.

**Comment by Savagepvppanda** [comment]
thanks it works life saver you are
